trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'PublishingTrackerConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create \
        --location westeurope \
        --template-file main.bicep \
        --parameters sqlAdminUsername='adminuser' sqlAdminPassword='$(sqlPassword)'
